### ISSUE TITLE
Graphic glitch in emulator

### ISSUE THREAD

**Issue by LostLinky** [hylian-modding/ModLoader64#24]
OS: Windows 10 64-bit
Graphics: Intel HD Graphics 4000

Emulator is showing a image glitch

Also tested on standalone Mupen64 Plus using the default graphics plugin and had no issue there.

Any help is appreciated

Image below:
![image](https://user-images.githubusercontent.com/90572041/144918095-19e6f94d-0ce9-492d-9c90-1aba10a8e1fa.png)

**Comment by Drahsid** [comment]
I don't think you read the FAQ. How did you even get here before doing that?
