### ISSUE TITLE
Gulp installation not compatible with Fish

### ISSUE THREAD

**Issue by nbennett320** [hylian-modding/ModLoader64#25]
Issuing the `yarn` command to install causes an error when using the Fish shell.
The Gulp task `api_link` fails, and the installation cannot be complete.
A simple fix is just to switch to Bash, just thought it would be worth mentioning here.

**Comment by denoflionsx** [comment]
We only test the Linux side of things against stock Ubuntu. We sort of assume if one is using Linux they're prepared to figure things out themselves.

If this isn't something @PapaSmurf-ML64 wants to look into he can close it.

**Comment by PapaSmurf-ML64** [comment]
As far as I'm aware, Fish shell is 100% a user choice to install and use and no distro on Earth comes with it, nor defaults to it. The issue lies with Fish shell, not ModLoader64, so it's not something we intend to try to fix.

**Comment by Drahsid** [comment]
I actually want to reopen this for just a moment, it might be possible to avoid this issue if we make a shell script that declares bash as the interpreter.

For example:
```sh
#!/bin/bash
npm install -g yarn
npm install -g typescript
npm install -g gulp-cli
yarn
yarn link
```

Though obviously this requires bash to be installed... but who doesn't have bash installed?
