### ISSUE TITLE
Falla de imagen TLoZ MM

### ISSUE THREAD

**Issue by JosuMajor04** [hylian-modding/ModLoader64#35]
tengo problemas con la imagen del juego

NECESITO AYUDA

no sé como solucionar este problema

![image](https://user-images.githubusercontent.com/121350866/209442589-d0c8e7dd-15e9-4697-a6ae-821b7a2d4de0.png)

**Comment by PapaSmurf-ML64** [comment]
Check #faq in the ModLoader64 Discord server.
